### ISSUE TITLE
Make content accessible for screen readers

### ISSUE THREAD

**Issue by andreastai** [w3c/dapt-reqs#4]
It would be good if the diagram and the tables are accessible to screen readers. From my first checks, there seem to be some difficulties.

**Comment by cconcolato** [comment]
We should add a paragraph before the diagram indicating that some blocks in the diagram are clickable and link to the corresponding process description.

We should also try to fix the tooltips which are generic (Canvas 1, Bezier, ...) by simply removing them. 

We should add an alt-text on the image.

**Comment by gkatsev** [comment]
The tooltips come from the titles of the SVG. For example
https://github.com/w3c/dapt-reqs/blob/71316d03b7c1374597b8d9133204dad4ccae9729/figures/workflow-fig.svg?short_path=055db1a#L18

Those could be updated to be more descriptive

**Comment by nigelmegitt** [comment]
I've tried to navigate this with VoiceOver and it's quite tricky. This change does seem to help. The other thing that would help is possibly to assign some kind of label for the "X" labels.

**Comment by nigelmegitt** [comment]
#8 helps a bit with the SVG image. VoiceOver on the Mac, with Safari, reads the caption of the image, so I don't think it needs any more alt text. It also reads the contents of each box, but there's no easy way to navigate the arrows in a natural way.

**Comment by andreastai** [comment]
Thanks for your efforts @nigelmegitt @cconcolato I think the overall goal needs to be that with a screen reader you can get the same information about the sequence of steps in the workflow as with the visuals. If this is not possible with adding metadata to the SVG then a long description in the alt text may be of help.

**Comment by nigelmegitt** [comment]
The table below is that long description though, or should be. The SVG should be a visual shorthand and all the information in it needs to be in text, so a long alt description shouldn't be needed. 

I could certainly believe there are things we should do to make the tabular data better. Maybe it should not be a table of process steps at all, but a sequence of headed paragraphs?

**Comment by nigelmegitt** [comment]
I'm going to try changing the table in §2 into separate paragraphs to see how that works.

**Comment by andreastai** [comment]
@nigelmegitt If you haven't seen it already the [W3C WAI Tables Tutorial](https://www.w3.org/WAI/tutorials/tables/#:~:text=Accessible%20tables%20need%20HTML%20markup,td%3E%20to%20make%20tables%20accessible.) may be of help.

**Comment by nigelmegitt** [comment]
Thanks @andreastai . My work in progress is looking quite pleasing to me. It's more text-heavy but easier to read and understand, possibly for all readers. I'll complete it and push it and we can decide whether to adopt or not.

**Comment by andreastai** [comment]
@nigelmegitt Great! One thing I noticed from the table is that it does not include information about the produced artefacts and whether these artefacts are in scope of the specification.

**Comment by nigelmegitt** [comment]
Yes, I noticed that too @andreastai , and the new format allows me to add that information more easily - I've already begun to do that. I will also include pointers to the previous and following steps.

**Comment by nigelmegitt** [comment]
Done in #9 .

**Comment by nigelmegitt** [comment]
I think #10 should be enough to close this issue, unless there are any more obvious problems right now.

**Comment by andreastai** [comment]
> I think #10 should be enough to close this issue, unless there are any more obvious problems right now.

Yes! Thanks, @nigelmegitt for addressing the issue!

**Comment by himorin** [comment]
so, ready to as a transition to DNOTE on /TR/ for this WG NOTE? (would be touched in WG call today, although?)

**Comment by nigelmegitt** [comment]
> so, ready to as a transition to DNOTE on /TR/ for this WG NOTE? (would be touched in WG call today, although?)

Yes. No objection since resolution was made, and will confirm during the WG call.

**Comment by nigelmegitt** [comment]
Just to avoid confusion the links from #18 were a mistake, it should have referred to #17.
