### ISSUE TITLE
Update Requirement R2 and Timing

### ISSUE THREAD

**Issue by cconcolato** [w3c/dapt-reqs#6]
From @nigelmegitt : 
> In ADPT, the requirement for intervals was distinct from the requirements their contents - any reason not to do the same here?

**Comment by cconcolato** [comment]
I'm not sure I understand the comment. Can you elaborate?

**Comment by nigelmegitt** [comment]
Just trying to make each requirement as granular as possible.

The current wording brings the timed interval requirement together with "matching a dialogue spoken by a single character or matching on-screen text from the programme, or that is an opportunity for adding descriptions."

My thinking is that the definition of an interval is one thing, and the requirements for intervals that support each of those different types of content can be listed distinctly. That makes it easier to test whether the specification meets each requirement individually.

**Comment by nigelmegitt** [comment]
Closing with no action - the definition of ~event~ Script event that we have does not require anything other than the times: the content is then optional.
