### ISSUE TITLE
Event term

### ISSUE THREAD

**Issue by cconcolato** [w3c/dapt-reqs#7]
@nigelmegitt said:
> Is "event" the best name? Do nested events need a different term?

**Comment by cconcolato** [comment]
Can you elaborate on "nested events", maybe with an example?

**Comment by nigelmegitt** [comment]
The definition of event as it stands now suggests there's a single list of entities defined by begin and end times, but in practice there may be nested timed elements - are they _all_ "events" or are only the outermost ones events?

There's an example of such nested timed elements at https://w3c.github.io/adpt/#example-5

**Comment by nigelmegitt** [comment]
TTWG Call 2022-09-15: Considered these options:

* Speech event
* Event
* Script event
* Script interval

Decided to try Script Event.

Re nesting, a Script Event is the high level concept/thing/entity that authors deal with, and within each one there can be timed steps, which we aren't calling "nested script events" or "subevents" etc.
